"""Write a concise, auditable Markdown report from finished TTT analyses.

The script is read-only with respect to experiment outputs: it consumes the
audit and summary tables generated by scripts 226/227 and writes only a report
under the comparison namespace.  It never changes thresholds or rescoring.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd

ROOT = Path("/root/b_false_alarm_atlas")
OUT = ROOT / "outputs/reports/cbramod-ttt-method-comparison-v1"


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text()) if path.exists() else {}


def fmt(value: Any) -> str:
    if value is None:
        return "NA"
    try:
        if pd.isna(value):
            return "NA"
    except Exception:
        pass
    if isinstance(value, float):
        return f"{value:.4f}"
    return str(value)


def main() -> None:
    audit = read_json(OUT / "audit.json")
    analysis = read_json(OUT / "analysis_manifest.json")
    summary_path = OUT / "method_fold_macro_summary.csv"
    paired_path = OUT / "paired_deltas_adapted_minus_frozen.csv"
    summary = pd.read_csv(summary_path) if summary_path.exists() else pd.DataFrame()
    paired = pd.read_csv(paired_path) if paired_path.exists() else pd.DataFrame()
    lines = [
        "# CBraMod test-time adaptation method comparison",
        "",
        f"Status: **{audit.get('status', 'INCOMPLETE')}**; analysis status: **{analysis.get('status', 'INCOMPLETE')}**.",
        "",
        "This report compares three distinct adaptation directions on CHB-MIT with frozen patient-level GroupKFold assignments:",
        "(1) joint supervised detection plus masked-patch reconstruction at source training, followed by unlabeled reconstruction TTT;",
        "(2) first-order MT3/FOMAML-style support reconstruction and query detection meta-training, followed by the same unlabeled TTT;",
        "(5) a source-trained temporal label-space prior used as validation-gated output post-processing.",
        "The experiments are method studies rather than additional seizure-detector architectures.",
        "",
        "## Primary aggregation",
        "",
        analysis.get("primary_aggregation", "Mean seeds within fold, then macro-average folds; repeated seed rows are not independent patients."),
        "The source detector rows are the existing frozen v3 GroupKFold test metrics; no new threshold search or test rerun is performed by this report.",
        "",
        "## Fold-macro test summary",
        "",
        "| Method | Condition | Folds | Sensitivity (mean ± fold SD) | FA/24h (mean ± fold SD) | Delay (mean ± fold SD) |",
        "|---|---|---:|---:|---:|---:|",
    ]
    if summary.empty:
        lines.append("| pending | pending | — | — | — | — |")
    else:
        for _, row in summary.sort_values(["method", "condition"]).iterrows():
            lines.append(
                f"| {row.get('method','')} | {row.get('condition','')} | {fmt(row.get('n_folds'))} | "
                f"{fmt(row.get('event_sensitivity_fold_macro_mean'))} ± {fmt(row.get('event_sensitivity_fold_macro_sd'))} | "
                f"{fmt(row.get('fa_per_24h_fold_macro_mean'))} ± {fmt(row.get('fa_per_24h_fold_macro_sd'))} | "
                f"{fmt(row.get('detection_delay_mean_s_fold_macro_mean'))} ± {fmt(row.get('detection_delay_mean_s_fold_macro_sd'))} |"
            )
    lines += ["", "## Paired adapted-minus-frozen differences", "", "| Method | Fold | Seed | Δ sensitivity | Δ FA/24h |", "|---|---:|---:|---:|---:|"]
    if paired.empty:
        lines.append("| pending | — | — | — | — |")
    else:
        for _, row in paired.sort_values(["method", "fold", "seed"]).iterrows():
            lines.append(f"| {row.method} | {int(row.fold)} | {int(row.seed)} | {fmt(row.delta_event_sensitivity_adapted_minus_frozen)} | {fmt(row.delta_fa_per_24h_adapted_minus_frozen)} |")
    lines += [
        "",
        "## Interpretation rule",
        "",
        "A method is considered practically promising only if its validation gate preserves sensitivity within 3 percentage points of the appropriate frozen comparator and its held-out test result lowers FA/24h. A failure to meet this rule is retained as a negative result; no test threshold is changed after evaluation.",
        "",
        "## Audit status",
        "",
        f"Training/evaluation audit: **{audit.get('status', 'INCOMPLETE')}**. Missing or failed runs are listed in `audit.json`; they are not silently omitted.",
        "",
        "Generated from frozen manifests and metrics; this file is descriptive and does not authorize a new experiment.",
        "",
    ]
    (OUT / "final_report.md").write_text("\n".join(lines))
    print("wrote", OUT / "final_report.md")


if __name__ == "__main__":
    main()
